Repository travelping/upg-vpp, pull requests merged in 2021-06, with the labels that each got.

#128 Add DPDK package to the images
  Dockerfile
  Dockerfile.devel
Labels: enhancement

#127 [stable backport] Add DPDK package to the images
  Dockerfile
  Dockerfile.devel
Labels: backport, enhancement

#132 Install libnuma1 and rm clang9 in the docker images
  Dockerfile
  Dockerfile.devel
Labels: fix

#133 [stable backport] Install libnuma1 in the docker images
  Dockerfile
  Dockerfile.devel
Labels: backport, fix

#134 [Stable] [Backport] Don't reject duplicate FARs with NAT for same UE IP
  upf/upf_pfcp_api.c
Labels: backport

#139 [Stable] [Backport] [UPG-NAT] Per pool stats binary API
  upf/upf.api
  upf/upf_api.c
  upf/upf_test.c
Labels: backport

#143 [Stable] [Backport] Fix memleak in BBF FAR processing and port range calculation for binding
  upf/upf_pfcp_api.c
  vpp-patches/0015-Controlled-NAT-function.patch
Labels: backport

#149 [stable backport] Fix wrong message field termination
  upf/upf_api.c
Labels: backport, fix
