Repository travelping/upg-vpp, pull requests merged in 2022-04, with the labels that each got.

#229 Update vpp-base with vpp 22.02 and golang 1.17
  vpp.spec
Labels: enhancement

#231 Remove VTIME out of measurement methods
  test/e2e/framework/sessionconfig.go
  upf/upf_pfcp.c
Labels: fix

#230 [CLI] Add loop termination for NAT/UEIP pool commands
  upf/upf_cli.c
Labels: bug
